const UserActionTypes = {
    ADD_PERSON:"ADD_PERSON",
    DELETE_PERSON:"DELETE_PERSON",
    SET_CURRENT_USER:"SET_CURRENT_USER",
    SET_MAIN_STREAM:"SET_MAIN_STREAM",
    UPDATE_CURRENT_USER:"UPDATE_CURRENT_USER",
    UPDATE_MEETJOINER:"UPDATE_MEETJOINER"
}

export default UserActionTypes;